# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: David Besserman
title: Senior Software Engineer
# email: brett.h@email.co.uk
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username:  dbesserman
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: dbesserman
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's David. I majored in economics but I realy found myself when I started coding. I'm most skilled in <mark>Ruby</mark> (with or without rails). Occasionally I like to explore the latest javascript front-end framework and I have a soft spot for <mark>Elixir</mark>.

# Projects Section
projects_title: Community Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Bouldering
   - Piano
   - The latest HBO show
   - Tennis

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
